#!/usr/bin/sh

if [ $# -lt 2 ]
then
	echo "Usage is: $0 <numsvrs> <start port no.>"
	exit 
fi

n=$1
port=$2

echo "Starting $n Servers with port starting from $port"

. /etc/pbs.conf

ulimit -n 10000
ulimit -c unlimited

i=1
while [ $i -le $n ]
do
	export PBS_BATCH_SERVICE_PORT=$port
	echo starting Server $i
	$PBS_EXEC/sbin/pbs_server
	
	i=`expr $i + 1`
	port=`expr $port + 1`
done

echo "Done"
