/*
 * Copyright (C) 1994-2018 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */


/**
 * @file    node_recov_db.c
 *
 * @brief
 *		nodejob_recov_db.c - This file contains the functions to record a node-job
 *		data structure to database and to recover it from database.
 *
 * Included functions are:
 * 	initialize_nodejob_db_obj()
 *	nodejob_recov_db()
 *	nodejob_db_to_attrlist()
 *	clear_nodejob_dbobj()
 *	nodejob_update_attr_db()
 */


#include <pbs_config.h>   /* the master config generated by configure */

#include <stdio.h>
#include <sys/types.h>

#ifndef WIN32
#include <sys/param.h>
#endif

#include "pbs_ifl.h"
#include <errno.h>
#include <fcntl.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

#include <unistd.h>
#include "server_limits.h"
#include "list_link.h"
#include "attribute.h"

#ifdef WIN32
#include <sys/stat.h>
#include <io.h>
#include <windows.h>
#include "win.h"
#endif

#include "log.h"
#include "attribute.h"
#include "list_link.h"
#include "server_limits.h"
#include "credential.h"
#include "libpbs.h"
#include "batch_request.h"
#include "pbs_nodes.h"
#include "job.h"
#include "resource.h"
#include "reservation.h"
#include "queue.h"
#include "svrfunc.h"
#include <memory.h>
#include "libutil.h"
#include "pbs_db.h"


pbs_db_nodejob_info_t *
initialize_nodejob_db_obj(char *nd_name, char *job_id, int is_resv) {
	pbs_db_nodejob_info_t	*db_obj;

	db_obj = (pbs_db_nodejob_info_t *) malloc(sizeof(pbs_db_nodejob_info_t));

	if (job_id)
		strncpy(db_obj->job_id, job_id, PBS_MAXSVRJOBID);
	else
		db_obj->job_id[0] = '\0';
	strncpy(db_obj->nd_name, nd_name, PBS_MAXSERVERNAME);
	db_obj->is_resv = is_resv;
	db_obj->admn_suspend = 0;
	db_obj->attr_list.attr_count = 0;
	db_obj->attr_list.attributes = NULL;

	return db_obj;
}

/**
 * @brief
 *		Recover a nodejob from the database
 *
 * @param[in]	nj	- Information about the nodejob to recover
 *
 * @return	return code
 * @retval	!0 - Failure
 * @retval	0 - Success
 */
int
nodejob_recov_db(void *nj)
{
	pbs_db_obj_info_t obj;
	int rc = 0;
	pbs_db_conn_t *conn = (pbs_db_conn_t *) svr_db_conn;

	obj.pbs_db_obj_type = PBS_DB_NODEJOB;
	obj.pbs_db_un.pbs_db_nodejob = (pbs_db_nodejob_info_t *) nj;

	if ((rc = pbs_db_begin_trx(conn, 0, 0)) != 0)
		goto db_err;

	if ((rc = pbs_db_load_obj(conn, &obj, 0)) < 0)
		goto db_err;

	if ((rc = pbs_db_end_trx(conn, PBS_DB_COMMIT)) != 0)
		goto db_err;

	return 0;

db_err:
	log_err(-1, "nodejob_recov_db", "error on recovering nodejob table");
	(void) pbs_db_end_trx(conn, PBS_DB_ROLLBACK);
	pbs_db_reset_obj(&obj);
	return rc;
}

void
append_to_joblist(pbs_node *pnode, char *jobid, int ncpus)
{	
	struct pbs_job_list *jlist;

	DBPRT(("Entering: %s", __func__))

	if (pnode->job_list == NULL) {
		pnode->job_list = malloc(sizeof(struct pbs_job_list));
		pnode->job_list->job_str = malloc(1024);
		pnode->job_list->buf_sz = 1024;
		pnode->job_list->offset = 0;
		pnode->job_list->last_cpu_indx = 0;
	}
	
	jlist = pnode->job_list;
	if (jlist->offset + (strlen(jobid) + 15) * ncpus > jlist->buf_sz) {
		char *tmp_str = realloc(jlist->job_str, jlist->buf_sz * 2);
		if (tmp_str != NULL) {
			jlist->job_str = tmp_str;
			jlist->buf_sz *= 2;
		}
	}

	do {
		if (jlist->offset != 0) {
			jlist->offset +=sprintf(jlist->job_str + jlist->offset, ", ");
		}
		jlist->offset += sprintf(jlist->job_str + jlist->offset,
					 "%s/%ld", jobid, jlist->last_cpu_indx);
		if (ncpus)
			jlist->last_cpu_indx += 1;
	} while(--ncpus > 0);
}

void
append_to_resvlist(pbs_node *pnode, char *resvid)
{	
	struct pbs_job_list *rlist;

	DBPRT(("Entering: %s", __func__))

	if (pnode->resv_list == NULL) {
		pnode->resv_list = malloc(sizeof(struct pbs_job_list));
		pnode->resv_list->job_str = malloc(1024);
		pnode->resv_list->buf_sz = 1024;
		pnode->resv_list->offset = 0;
		pnode->resv_list->last_cpu_indx = 0;
	}
	
	rlist = pnode->resv_list;
	if (rlist->offset + strlen(resvid) >= rlist->buf_sz) {
		char *tmp_str = realloc(rlist->job_str, rlist->buf_sz * 2);
		if (tmp_str != NULL) {
			rlist->job_str = tmp_str;
			rlist->buf_sz *= 2;
		}
	}

	if (rlist->offset != 0) {
		rlist->offset +=sprintf(rlist->job_str + rlist->offset, ", ");
	}
	rlist->offset += sprintf(rlist->job_str + rlist->offset, "%s", resvid);
}

int
nodejob_db_to_attrlist(struct pbsnode *pnode, pbs_db_nodejob_info_t *db_obj)
{
	int i;
	attribute    *pattr = &pnode->nd_attr[(int)ND_ATR_ResourceAssn];

	DBPRT(("----------------Entering nodejob_db_to_attrlist()------------"))

	for (i = 0; i < db_obj->attr_list.attr_count; i++) {
		attribute tmpattr;
		pbs_db_attr_info_t *attrs = &db_obj->attr_list.attributes[i];

		if (strcmp(attrs->attr_name, ATTR_rescassn))
			continue;
		memset(&tmpattr, 0, sizeof(attribute));
		if ((node_attr_def + ND_ATR_ResourceAssn)->at_decode) {
			(void)(node_attr_def + ND_ATR_ResourceAssn)->at_decode(
							&tmpattr, attrs->attr_name,
							attrs->attr_resc,
							attrs->attr_value);
		}
		/* Add to job list whenever we encounter "ncpus" resource. */
		if (strcmp(attrs->attr_resc, "ncpus") == 0 && db_obj->is_resv == PBS_NODEJOB_JOB) {
			append_to_joblist(pnode, db_obj->job_id, atol(attrs->attr_value));
		}
		(void)(node_attr_def + ND_ATR_ResourceAssn)->at_set(pattr, &tmpattr, INCR);
	}
	if (db_obj->is_resv == PBS_NODEJOB_RESV)
		append_to_resvlist(pnode, db_obj->job_id);

	return 0;
}


void
clear_nodejob_dbobj(pbs_db_nodejob_info_t *db_obj)
{
	pbs_db_obj_info_t obj;

	obj.pbs_db_obj_type = PBS_DB_NODEJOB;
	obj.pbs_db_un.pbs_db_nodejob = db_obj;
	pbs_db_reset_obj(&obj);
	free(db_obj);
}

/**
 * @brief
 *	Save a nodejob attributes to the database.
 *
 * @param[in]	pnodejob- Pointer to the nodejob to save
 *
 * @return      Error code
 * @retval	0 - Success
 * @retval	-1 - Failure
 *
 */
int
nodejob_update_attr_db(pbs_db_nodejob_info_t *dbnode)
{
	pbs_db_obj_info_t obj;
	pbs_db_conn_t *conn = (pbs_db_conn_t *) svr_db_conn;

	obj.pbs_db_obj_type = PBS_DB_NODEJOB;
	obj.pbs_db_un.pbs_db_nodejob = dbnode;

	DBPRT(("dbnode->nd_name: %s, dbnode->job_id: %s", dbnode->nd_name, dbnode->job_id))

	if (pbs_db_add_update_attr_obj(conn, &obj, dbnode->nd_name, &dbnode->attr_list) != 0) {
		if (pbs_db_save_obj(conn, &obj, PBS_INSERT_DB) != 0) {
			goto db_err;
		}
	}

	clear_nodejob_dbobj(dbnode);

	return (0);
db_err:
	strcpy(log_buffer, "nodejob_save failed ");
	if (conn->conn_db_err != NULL)
		strncat(log_buffer, conn->conn_db_err, LOG_BUF_SIZE - strlen(log_buffer) - 1);
	log_err(-1, "node_save_db", log_buffer);
	panic_stop_db(log_buffer);
	return (-1);
}
