/*
 * Copyright (C) 1994-2018 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */


/**
 * @file    db_postgres_nodejob.c
 *
 * @brief
 *      Implementation of the node data access functions for postgres
 */

#include <pbs_config.h>   /* the master config generated by configure */
#include "pbs_db.h"
#include "db_postgres.h"

/**
 * @brief
 *	Prepare all the node related sqls. Typically called after connect
 *	and before any other sql exeuction
 *
 * @param[in]	conn - Database connection handle
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
pg_db_prepare_nodejob_sqls(pbs_db_conn_t *conn)
{
	snprintf(conn->conn_sql, MAX_SQL_LENGTH, "update pbs.node_job set "
			"nj_savetm = localtimestamp,"
			"attributes = attributes || hstore($3::text[]) "
			"where job_id = $1 and nd_name = $2");

	if (pg_prepare_stmt(conn, STMT_UPDATE_NODEJOBATTRS, conn->conn_sql, 3) != 0)
		return -1;

	snprintf(conn->conn_sql, MAX_SQL_LENGTH, "select "
		"job_id, "
		"nd_name, "
		"is_resv, "
		"subnode_ct, "
		"admn_suspend, "
		"hstore_to_array(attributes) as attributes "
		"from pbs.node_job "
		"where job_id = $1 and nd_name = $2 "
		"order by nj_creattm");
	if (pg_prepare_stmt(conn, STMT_SELECT_NODEJOB, conn->conn_sql, 2) != 0)
		return -1;

	snprintf(conn->conn_sql, MAX_SQL_LENGTH, "select "
		"job_id, "
		"nd_name, "
		"is_resv, "
		"subnode_ct, "
		"admn_suspend, "
		"hstore_to_array(attributes) as attributes "
		"from pbs.node_job "
		"where nd_name = $1 "
		"order by nj_creattm");
	if (pg_prepare_stmt(conn, STMT_FIND_NODEJOB_USING_NODEID, conn->conn_sql, 1) != 0)
		return -1;

	snprintf(conn->conn_sql, MAX_SQL_LENGTH, "insert into pbs.node_job("
		"job_id, "
		"nd_name, "
		"is_resv, "
		"subnode_ct, "
		"admn_suspend, "
		"nj_creattm, "
		"nj_savetm, "
		"attributes "
		") "
		"values "
		"($1, $2, $3, $4, $5, localtimestamp, localtimestamp, hstore($6::text[]))");

	if (pg_prepare_stmt(conn, STMT_INSERT_NODEJOB, conn->conn_sql, 6) != 0)
		return -1;

	/* in case of nodes do not use || with existing attributes, since we re-write all attributes */
	snprintf(conn->conn_sql, MAX_SQL_LENGTH, "update pbs.node_job set "
		"is_resv = $3, "
		"subnode_ct = $4, "
		"admn_suspend = $5, "
		"nj_savetm = localtimestamp, "
		"attributes = hstore($6::text[]) "
		" where job_id = $1 and nd_name = $2");
	if (pg_prepare_stmt(conn, STMT_UPDATE_NODEJOB, conn->conn_sql, 6) != 0)
		return -1;

	snprintf(conn->conn_sql, MAX_SQL_LENGTH, "delete from pbs.node_job where job_id = $1");
	if (pg_prepare_stmt(conn, STMT_DELETE_NODEJOB, conn->conn_sql, 1) != 0)
		return -1;

	return 0;
}


/**
 * @brief
 *	Load node-job data from the row into the node-job object
 *
 * @param[in]	res - Resultset from a earlier query
 * @param[in]	pnd  - Node object to load data into
 * @param[in]	row - The current row to load within the resultset
 *
 * @return      Error code
 * @retval	-1 - On Error
 * @retval	 0 - On Success
 * @retval	>1 - Number of attributes
 * @retval 	-2 -  Success but data same as old, so not loading data (but locking if lock requested)
 *
 */
static int
load_nodejob(PGresult *res, pbs_db_nodejob_info_t *pnd, int row)
{
	char *raw_array;
	//BIGINT db_savetm;
	static int job_id_fnum, nd_name_fnum, is_resv_fnum, subnode_ct_fnum, admn_suspend_fnum, attributes_fnum;
	static int fnums_inited = 0;

	if (fnums_inited == 0) {
		job_id_fnum = PQfnumber(res, "job_id");
		nd_name_fnum = PQfnumber(res, "nd_name");
		is_resv_fnum = PQfnumber(res, "is_resv");
		subnode_ct_fnum = PQfnumber(res, "subnode_ct");
		admn_suspend_fnum = PQfnumber(res, "admn_suspend");
		attributes_fnum = PQfnumber(res, "attributes");
		fnums_inited = 1;
	}

#if 0
	GET_PARAM_BIGINT(res, row, db_savetm, ji_savetm_fnum);
	if (pj->ji_savetm == db_savetm) {
		/* data same as read last time, so no need to read any further, return success from here */
		/* however since we loaded data from the database, the row is locked if a lock was requested */
		return -2;
	}
	pj->ji_savetm = db_savetm;  /* update the save timestamp */
#endif

	GET_PARAM_STR(res, row, pnd->job_id, job_id_fnum);
	GET_PARAM_STR(res, row, pnd->nd_name, nd_name_fnum);
	GET_PARAM_INTEGER(res, row, pnd->is_resv, is_resv_fnum);
	GET_PARAM_INTEGER(res, row, pnd->subnode_ct, subnode_ct_fnum);
	GET_PARAM_INTEGER(res, row, pnd->admn_suspend, admn_suspend_fnum);
	GET_PARAM_BIN(res, row, raw_array, attributes_fnum);

	/* convert attributes from postgres raw array format */
	return (convert_array_to_db_attr_list(raw_array, &pnd->attr_list));
}

/**
 * @brief
 *	Insert nodejob data into the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Information of nodejob to be inserted
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 *
 */
int
pg_db_save_nodejob(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int savetype)
{
	pbs_db_nodejob_info_t *pndjob = obj->pbs_db_un.pbs_db_nodejob;
	char *stmt;
	int params;
	char *raw_array = NULL;

	SET_PARAM_STR(conn, pndjob->job_id, 0);
	SET_PARAM_STR(conn, pndjob->nd_name, 1);
	SET_PARAM_INTEGER(conn, pndjob->is_resv, 2);
	SET_PARAM_INTEGER(conn, pndjob->subnode_ct, 3);
	SET_PARAM_INTEGER(conn, pndjob->admn_suspend, 4);

	if (savetype == PBS_UPDATE_DB_QUICK) {
		params = 5;
	} else {
		int len = 0;
		/* convert attributes to postgres raw array format */
		if ((len = convert_db_attr_list_to_array(&raw_array, &pndjob->attr_list)) <= 0)
			return -1;

		SET_PARAM_BIN(conn, raw_array, len, 5);
		params = 6;
	}

	if (savetype == PBS_UPDATE_DB_FULL)
		stmt = STMT_UPDATE_NODEJOB;
	else
		stmt = STMT_INSERT_NODEJOB;

	if (pg_db_cmd(conn, stmt, params) != 0) {
		free(raw_array);
		return -1;
	}

	free(raw_array);

	return 0;
}

/**
 * @brief
 *	Add or update attributes of a node_job table
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Node information
 * @param[in]	node_id  - Node name
 * @param[in]	attr_list - List of attributes
 *
 * @return      Error code
 * @retval	-1 - Execution of prepared statement failed
 * @retval	 0 - Success and > 0 rows were affected
 * @retval	 1 - Execution succeeded but statement did not affect any rows
 *
 */
int
pg_db_add_update_attr_nodejob(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, void *node_id, pbs_db_attr_list_t *attr_list)
{
	char *raw_array = NULL;
	int len = 0;
	pbs_db_nodejob_info_t *pnj = obj->pbs_db_un.pbs_db_nodejob;

	if ((len = convert_db_attr_list_to_array(&raw_array, attr_list)) <= 0)
		return -1;
	SET_PARAM_STR(conn, pnj->job_id, 0);
	SET_PARAM_STR(conn, node_id, 1);

	SET_PARAM_BIN(conn, raw_array, len, 2);

	if (pg_db_cmd(conn, STMT_UPDATE_NODEJOBATTRS, 3) != 0) {
		free(raw_array);
		return -1;
	}

	free(raw_array);

	return 0;
}

/**
 * @brief
 *	Load node-job data from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Load node information into this object
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	>1 - Number of attributes
 * @retval 	-2 -  Success but data same as old, so not loading data (but locking if lock requested)
 *
 */
int
pg_db_load_nodejob(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj, int lock)
{
	PGresult *res;
	int rc;
	pbs_db_nodejob_info_t *pnj = obj->pbs_db_un.pbs_db_nodejob;

	SET_PARAM_STR(conn, pnj->job_id, 0);
	SET_PARAM_STR(conn, pnj->nd_name, 1);
	if ((rc = pg_db_query(conn, STMT_SELECT_NODEJOB, 2, lock, &res)) != 0)
		return rc;

	rc = load_nodejob(res, pnj, 0);

	PQclear(res);
	return rc;
}

/**
 * @brief
 *	Find nodejob
 *
 * @param[in]	conn - Connection handle
 * @param[in]	st   - The cursor state variable updated by this query
 * @param[in]	obj  - Information of nodejob to be found
 * @param[in]	opts - Any other options (like flags, timestamp)
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 - Success, but no rows found
 *
 */
int
pg_db_find_nodejob(pbs_db_conn_t *conn, void *st, pbs_db_obj_info_t *obj,
	pbs_db_query_options_t *opts)
{
	PGresult *res;
	int rc;
	pg_query_state_t *state = (pg_query_state_t *) st;
	pbs_db_nodejob_info_t *pnj = obj->pbs_db_un.pbs_db_nodejob;

	if (!state)
		return -1;

	SET_PARAM_STR(conn, pnj->nd_name, 0);
	if ((rc = pg_db_query(conn, STMT_FIND_NODEJOB_USING_NODEID, 1, 0, &res)) != 0)
		return rc;

	state->row = 0;
	state->res = res;
	state->count = PQntuples(res);
	return 0;
}

/**
 * @brief
 *	Get the next nodejob from the cursor
 *
 * @param[in]	conn - Connection handle
 * @param[in]	st   - The cursor state
 * @param[in]	obj  - Node information is loaded into this object
 *
 * @return      Error code
 *		(Even though this returns only 0 now, keeping it as int
 *			to support future change to return a failure)
 * @retval	 0 - Success
 *
 */
int
pg_db_next_nodejob(pbs_db_conn_t *conn, void *st, pbs_db_obj_info_t *obj)
{
	PGresult *res = ((pg_query_state_t *) st)->res;
	pg_query_state_t *state = (pg_query_state_t *) st;

	return (load_nodejob(res, obj->pbs_db_un.pbs_db_nodejob, state->row));
}

/**
 * @brief
 *	Frees allocate memory of an Object
 *
 * @param[in]	obj - pbs_db_obj_info_t containing the DB object
 *
 * @return None
 *
 */
void
pg_db_reset_nodejob(pbs_db_obj_info_t *obj)
{
	free_db_attr_list(&(obj->pbs_db_un.pbs_db_nodejob->attr_list));
}

/**
 * @brief
 *	Delete the nodejob from the database
 *
 * @param[in]	conn - Connection handle
 * @param[in]	obj  - Node information
 *
 * @return      Error code
 * @retval	-1 - Failure
 * @retval	 0 - Success
 * @retval	 1 - Success but no rows deleted
 *
 */
int
pg_db_delete_nodejob(pbs_db_conn_t *conn, pbs_db_obj_info_t *obj)
{
	pbs_db_nodejob_info_t *pnd = obj->pbs_db_un.pbs_db_nodejob;
	SET_PARAM_STR(conn, pnd->job_id, 0);
	return (pg_db_cmd(conn, STMT_DELETE_NODEJOB, 1));
}
